services:
  - type: web
    name: dm-grab-extractor
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 180 --workers 2"
    envVars:
      - key: INTERNAL_TOKEN
        sync: false
